In [ ]:
import pandas as pd 
import os, sys
import os.path as osp   
import numpy as np

In [11]:
sys.path.append(osp.join(os.getcwd(), "..", "scripts"))

In [2]:
pd.read_pickle(osp.join("..", "test_folder", "StoppedMuons.dat"))

{'id': array([138674364, 138674401, 138674403, ..., 139298157, 139298163,
        139298231]),
 'reco': array([[0.87305975],
        [0.1561065 ],
        [0.48945266],
        ...,
        [0.9384998 ],
        [0.3683898 ],
        [0.5077752 ]], dtype=float32),
 'targets': array([[0.],
        [0.],
        [0.],
        ...,
        [1.],
        [1.],
        [1.]], dtype=float32),
 'Ns': array([ 14,  37, 115, ...,   9,  41,  21], dtype=int32),
 'metrics': {'binary_accuracy': 0.7944803237915039,
  'AUC': 0.8501608774702292,
  'TestLoss': 0.43629757}}

In [3]:
x, y = pd.read_pickle(os.path.join("..", "data", "features", "OscNextCommonSplit_full", "test0.dat"))

In [5]:
import matplotlib.pyplot as plt 

np.concatenate(x)

array([[ 4.62900009e+01, -3.48800011e+01, -4.01130005e+02,
         1.02420000e+04,  1.32500005e+00,  8.00000000e+00],
       [ 9.04899979e+01,  8.23499985e+01, -3.32350006e+02,
         1.21790000e+04,  1.02499998e+00,  8.00000000e+00],
       [ 7.23700027e+01, -6.65999985e+01, -4.47179993e+02,
         1.09330000e+04,  8.24999988e-01,  8.00000000e+00],
       ...,
       [ 4.15999985e+01,  3.54900017e+01, -4.24230011e+02,
         9.87100000e+03,  2.17499995e+00,  1.00000000e+00],
       [ 4.15999985e+01,  3.54900017e+01, -4.24230011e+02,
         9.88100000e+03,  2.75000006e-01,  1.00000000e+00],
       [ 4.15999985e+01,  3.54900017e+01, -4.66279999e+02,
         1.04390000e+04,  2.75000006e-01,  8.00000000e+00]])

In [20]:
xs = np.concatenate(x)
plt.hist(xs[:100000, :].T)


KeyboardInterrupt: 

In [ ]:
plt.hist(np.concatenate(x)[:10000, 4])

In [ ]:
from scripts.he

In [13]:
from helper_functions import angles_to_units

In [14]:
import tensorflow as tf

In [18]:
tf.math.reduce_euclidean_norm(angles_to_units(tf.cast(y, tf.float32)[:, 1:]), axis = 1

<tf.Tensor: shape=(50000, 3), dtype=float32, numpy=
array([[ 0.05450379,  0.92277545,  0.38146403],
       [ 0.59346974, -0.7565063 , -0.27475786],
       [ 0.8200959 , -0.09244053, -0.56471   ],
       ...,
       [-0.25597286, -0.75487983,  0.60384965],
       [-0.01274581,  0.817685  ,  0.57552475],
       [-0.06072835, -0.773598  ,  0.63075995]], dtype=float32)>

In [1]:
import matplotlib.pyplot as plt

In [ ]:
cmap = plt.cmap.plasma 
colors = cmap[np.linspace(0, 1, 10)]